# Functions for sampling of a data frame or a vector

#' Bootstrap samples a vector, matrix or a data frame
#'
#' @description
#' Creates a given number of bootstrap samples of a vector or a data frame.
#'
#' @details
#' The bootstraps are generated by drawing random samples of indexes (vector)
#' or row indexes (matrix or data frame) with replacement.
#' The function `sboot()` is a S3 generic.
#' Works in parallel, if a parallel backend is registered via `future::plan()`.
#'
#' @returns a named list of vectors, matrices or data frames named with the
#' `boot_n` scheme, where `n` denotes the sample number.
#'
#' @param x an object, currently a vector (default), matrix or a data frame.
#' @param B an integer, the number of bootstrapped samples to be returned.
#' @param ... extra arguments passed to the methods.
#'
#' @export

  sboot <- function(x, B, ...) UseMethod('sboot')

#' @rdname sboot
#' @export sboot.default
#' @export

  sboot.default <- function(x, B, ...) {

    ## handles atomic vectors

    if(!is.atomic(x)) {

      stop("'x' has to be an atomic vector.", call. = FALSE)

    }

    stopifnot(is.numeric(B))

    B <- as.integer(B)

    vec_samples <-
      purrr::map(1:B, function(i) sample(x, length(x), replace = TRUE))

    rlang::set_names(vec_samples, paste0('boot_', 1:B))

  }

#' @rdname sboot
#' @export sboot.matrix
#' @export

  sboot.matrix <- function(x, B, ...) {

    ## handles matrices

    #if(!is.matrix(x)) stop("'x' has to be a matrix.", call. = FALSE)

    stopifnot(is.numeric(B))

    B <- as.integer(B)

    indexes <- 1:nrow(x)

    index_samples <- sboot(indexes, B = B)

    furrr::future_map(index_samples, ~x[.x, ])

  }

#' @rdname sboot
#' @export sboot.data.frame
#' @export

  sboot.data.frame <- function(x, B, ...) {

    sboot.matrix(x, B)

  }

# END -----
